/**
 * Automated Cartoon Factory — AI Script & Scene Planner
 *
 * Provider Hierarchy (Strictly Real AI Model Generation):
 * 1. Google Gemini (gemini-2.5-flash, gemini-2.0-flash, gemini-1.5-flash)
 * 2. Groq (llama-3.3-70b-versatile, llama-3.1-8b-instant, mixtral-8x7b-32768)
 * 3. OpenAI (gpt-4o-mini, gpt-4o)
 * 4. OpenRouter (Multi-model router)
 * 5. Cloudflare Workers AI (@cf/meta/llama-3.3-70b-instruct-fp8-fast, @cf/meta/llama-3.1-8b-instruct)
 *
 * NOTE: Deterministic fallback scripts have been completely removed per directive.
 * All scripts must be freshly generated by an active AI provider.
 */

const https = require('https');
const http = require('http');

const GEMINI_API_KEY = process.env.GEMINI_API_KEY || '';
const GROQ_API_KEY = process.env.GROQ_API_KEY || '';
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || '';
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || '';
const CLOUDFLARE_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID || '';
const CLOUDFLARE_API_TOKEN = process.env.CLOUDFLARE_API_TOKEN || '';

const DEFAULT_CHARACTER = 'Archie';

const SYSTEM_PROMPT = `You are the Lead Director and Screenwriter for an automated 2D/2.5D educational cartoon channel.
The main character is "${DEFAULT_CHARACTER}", a charismatic, curious, and witty animated explainer host.

TOPIC CATEGORIES:
Science, Technology, Money/Business, History, Everyday-Life Explanations, Investigations, and "What If?" stories.

RULES:
1. Generate an engaging 3 to 5 scene script for a fast-paced vertical video (30-60 seconds total).
2. Each scene MUST have:
   - "scene": integer (1, 2, 3...)
   - "duration": estimated seconds for narration (e.g. 5.0 to 10.0)
   - "dialogue": spoken lines by ${DEFAULT_CHARACTER} (snappy, conversational, educational, clear)
   - "character_action": EXACTLY ONE OF ["idle", "talking", "walking", "point_right", "point_left", "thinking", "laughing", "surprise", "excitement", "looking_left", "looking_right"]
   - "emotion": EXACTLY ONE OF ["neutral", "happy", "surprised", "curious", "excited", "thinking", "concerned", "laughing"]
   - "camera": EXACTLY ONE OF ["wide", "medium", "close_up", "medium_to_close", "pan_left", "pan_right"]
   - "objects": array of visual props/items in the scene (e.g. ["smartphone", "wifi_waves", "satellite"])
   - "background_style": visual environment theme (e.g. "tech_studio", "neon_tech_lab", "deep_space", "ocean_seabed", "candlestick_chart_market", "inside_computer")
   - "effects": array of 2D visual effects (e.g. ["signal_pulse", "glowing_wire", "floating_question_mark", "binary_rain"])
3. Output MUST be ONLY valid JSON matching this schema:
{
  "topic": "string",
  "title": "Short, punchy, high-CTR title (under 55 chars)",
  "character_name": "${DEFAULT_CHARACTER}",
  "target_duration_seconds": 45,
  "category": "science" | "technology" | "money_business" | "history" | "everyday_explanations" | "what_if",
  "scenes": [
    {
      "scene": 1,
      "duration": 7.5,
      "dialogue": "...",
      "character_action": "point_right",
      "emotion": "surprised",
      "camera": "medium_to_close",
      "objects": ["..."],
      "background_style": "...",
      "effects": ["..."]
    }
  ]
}
Do not output markdown code blocks or conversational commentary. ONLY valid JSON.`;

/**
 * Validate and sanitize episode JSON
 */
function validateAndCleanEpisode(rawJson, topic = '') {
  try {
    let data;
    if (typeof rawJson === 'string') {
      let clean = rawJson.replace(/<think>[\s\S]*?<\/think>/gi, '').replace(/<think>[\s\S]*/gi, '');
      clean = clean.replace(/```json/gi, '').replace(/```/g, '').trim();
      const firstBrace = clean.indexOf('{');
      const lastBrace = clean.lastIndexOf('}');
      if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        clean = clean.substring(firstBrace, lastBrace + 1);
      }
      data = JSON.parse(clean);
    } else {
      data = rawJson;
    }

    if (!data || !data.title || !Array.isArray(data.scenes) || data.scenes.length === 0) {
      return null;
    }

    const validActions = [
      'idle', 'talking', 'walking', 'point_right', 'point_left',
      'thinking', 'laughing', 'surprise', 'excitement', 'looking_left', 'looking_right'
    ];
    const validEmotions = [
      'neutral', 'happy', 'surprised', 'curious', 'excited', 'thinking', 'concerned', 'laughing'
    ];
    const validCameras = [
      'wide', 'medium', 'close_up', 'medium_to_close', 'pan_left', 'pan_right'
    ];

    const cleanScenes = data.scenes.map((s, idx) => ({
      scene: Number(s.scene || idx + 1),
      duration: Math.max(2.5, Math.min(25.0, Number(s.duration || 6.5))),
      dialogue: String(s.dialogue || '').trim(),
      character_action: validActions.includes(s.character_action) ? s.character_action : 'talking',
      emotion: validEmotions.includes(s.emotion) ? s.emotion : 'curious',
      camera: validCameras.includes(s.camera) ? s.camera : 'medium',
      objects: Array.isArray(s.objects) ? s.objects.map(String) : ['prop'],
      background_style: String(s.background_style || 'tech_studio'),
      effects: Array.isArray(s.effects) ? s.effects.map(String) : ['glow']
    })).filter(s => s.dialogue.length > 5);

    if (cleanScenes.length === 0) return null;

    const totalDuration = cleanScenes.reduce((sum, sc) => sum + sc.duration, 0);

    return {
      topic: String(data.topic || topic).trim(),
      title: String(data.title).replace(/["']/g, '').trim(),
      character_name: String(data.character_name || DEFAULT_CHARACTER),
      target_duration_seconds: Math.round(totalDuration),
      category: data.category || 'technology',
      scenes: cleanScenes
    };
  } catch (err) {
    console.warn('[Planner Validation Error]:', err.message);
    return null;
  }
}

/**
 * 1. Google Gemini Inference Call
 */
async function callGemini(topic) {
  if (!GEMINI_API_KEY) throw new Error('GEMINI_API_KEY not configured');

  const models = ['gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-flash'];

  for (const model of models) {
    try {
      console.log(`[AI Planner] Requesting Google Gemini (${model}) for topic: "${topic}"...`);
      const body = JSON.stringify({
        contents: [{
          parts: [{
            text: `${SYSTEM_PROMPT}\n\nTask: Create a fresh educational cartoon episode scene plan for: "${topic}". Return strictly raw JSON matching the schema.`
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 2500,
          responseMimeType: "application/json"
        }
      });

      const raw = await new Promise((resolve, reject) => {
        const req = https.request(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${GEMINI_API_KEY}`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(body)
          },
          timeout: 25000
        }, (res) => {
          let data = '';
          res.on('data', c => data += c);
          res.on('end', () => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
              try {
                const parsed = JSON.parse(data);
                const text = parsed.candidates?.[0]?.content?.parts?.[0]?.text || '';
                resolve(text);
              } catch (e) {
                reject(e);
              }
            } else {
              reject(new Error(`Gemini HTTP ${res.statusCode}: ${data.slice(0, 150)}`));
            }
          });
        });
        req.on('error', reject);
        req.on('timeout', () => { req.destroy(); reject(new Error('Gemini request timed out')); });
        req.write(body);
        req.end();
      });

      const cleaned = validateAndCleanEpisode(raw, topic);
      if (cleaned) {
        return { plan: cleaned, provider: `google/${model}` };
      }
    } catch (e) {
      console.warn(`[AI Planner] Gemini ${model} failed:`, e.message);
    }
  }
  throw new Error('All Gemini models failed');
}

/**
 * 2. Groq Inference Call
 */
async function callGroq(topic) {
  if (!GROQ_API_KEY) throw new Error('GROQ_API_KEY not configured');

  const models = ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'];

  for (const model of models) {
    try {
      console.log(`[AI Planner] Requesting Groq (${model}) for topic: "${topic}"...`);
      const body = JSON.stringify({
        model,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: `Create an educational cartoon episode scene plan for: "${topic}"` }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.7,
        max_tokens: 1800
      });

      const raw = await new Promise((resolve, reject) => {
        const req = https.request('https://api.groq.com/openai/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${GROQ_API_KEY}`,
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(body)
          },
          timeout: 25000
        }, (res) => {
          let data = '';
          res.on('data', c => data += c);
          res.on('end', () => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
              try {
                const parsed = JSON.parse(data);
                resolve(parsed.choices?.[0]?.message?.content || '');
              } catch (e) {
                reject(e);
              }
            } else {
              reject(new Error(`Groq HTTP ${res.statusCode}: ${data.slice(0, 150)}`));
            }
          });
        });
        req.on('error', reject);
        req.on('timeout', () => { req.destroy(); reject(new Error('Groq request timed out')); });
        req.write(body);
        req.end();
      });

      const cleaned = validateAndCleanEpisode(raw, topic);
      if (cleaned) {
        return { plan: cleaned, provider: `groq/${model}` };
      }
    } catch (e) {
      console.warn(`[AI Planner] Groq ${model} failed:`, e.message);
    }
  }
  throw new Error('All Groq models failed');
}

/**
 * 3. OpenAI Inference Call
 */
async function callOpenAI(topic) {
  if (!OPENAI_API_KEY) throw new Error('OPENAI_API_KEY not configured');

  const models = ['gpt-4o-mini', 'gpt-4o'];

  for (const model of models) {
    try {
      console.log(`[AI Planner] Requesting OpenAI (${model}) for topic: "${topic}"...`);
      const body = JSON.stringify({
        model,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: `Create an educational cartoon episode scene plan for: "${topic}"` }
        ],
        response_format: { type: 'json_object' },
        temperature: 0.7,
        max_tokens: 1800
      });

      const raw = await new Promise((resolve, reject) => {
        const req = https.request('https://api.openai.com/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${OPENAI_API_KEY}`,
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(body)
          },
          timeout: 25000
        }, (res) => {
          let data = '';
          res.on('data', c => data += c);
          res.on('end', () => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
              try {
                const parsed = JSON.parse(data);
                resolve(parsed.choices?.[0]?.message?.content || '');
              } catch (e) {
                reject(e);
              }
            } else {
              reject(new Error(`OpenAI HTTP ${res.statusCode}: ${data.slice(0, 150)}`));
            }
          });
        });
        req.on('error', reject);
        req.on('timeout', () => { req.destroy(); reject(new Error('OpenAI request timed out')); });
        req.write(body);
        req.end();
      });

      const cleaned = validateAndCleanEpisode(raw, topic);
      if (cleaned) {
        return { plan: cleaned, provider: `openai/${model}` };
      }
    } catch (e) {
      console.warn(`[AI Planner] OpenAI ${model} failed:`, e.message);
    }
  }
  throw new Error('All OpenAI models failed');
}

/**
 * 4. OpenRouter Inference Call
 */
async function callOpenRouter(topic) {
  if (!OPENROUTER_API_KEY) throw new Error('OPENROUTER_API_KEY not configured');

  const models = ['google/gemini-2.0-flash-001', 'meta-llama/llama-3.3-70b-instruct', 'deepseek/deepseek-chat', 'mistralai/mistral-small-3'];

  for (const model of models) {
    try {
      console.log(`[AI Planner] Requesting OpenRouter (${model})...`);
      const body = JSON.stringify({
        model,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: `Create an educational cartoon episode scene plan for: "${topic}". Return strictly valid JSON.` }
        ],
        temperature: 0.7,
        max_tokens: 1800
      });

      const raw = await new Promise((resolve, reject) => {
        const req = https.request('https://openrouter.ai/api/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${OPENROUTER_API_KEY}`,
            'Content-Type': 'application/json',
            'HTTP-Referer': 'https://voxam.ai',
            'X-Title': 'Voxam Cartoon Factory',
            'Content-Length': Buffer.byteLength(body)
          },
          timeout: 25000
        }, (res) => {
          let data = '';
          res.on('data', c => data += c);
          res.on('end', () => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
              try {
                const parsed = JSON.parse(data);
                resolve(parsed.choices?.[0]?.message?.content || '');
              } catch (e) {
                reject(e);
              }
            } else {
              reject(new Error(`OpenRouter HTTP ${res.statusCode}: ${data.slice(0, 150)}`));
            }
          });
        });
        req.on('error', reject);
        req.on('timeout', () => { req.destroy(); reject(new Error('OpenRouter timed out')); });
        req.write(body);
        req.end();
      });

      const cleaned = validateAndCleanEpisode(raw, topic);
      if (cleaned) {
        return { plan: cleaned, provider: `openrouter/${model}` };
      }
    } catch (e) {
      console.warn(`[AI Planner] OpenRouter ${model} failed:`, e.message);
    }
  }
  throw new Error('All OpenRouter models failed');
}

/**
 * 5. Cloudflare Workers AI Inference Call
 */
async function callCloudflareAI(topic) {
  if (!CLOUDFLARE_ACCOUNT_ID || !CLOUDFLARE_API_TOKEN) {
    throw new Error('Cloudflare credentials not configured');
  }

  const models = [
    '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    '@cf/meta/llama-3.1-8b-instruct',
    '@cf/mistral/mistral-7b-instruct-v0.1'
  ];

  for (const model of models) {
    try {
      console.log(`[AI Planner] Requesting Cloudflare AI (${model})...`);
      const url = `https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/run/${model}`;
      const body = JSON.stringify({
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: `Create an educational cartoon episode scene plan for: "${topic}". Return strictly valid JSON.` }
        ],
        max_tokens: 1800
      });

      const raw = await new Promise((resolve, reject) => {
        const req = https.request(url, {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${CLOUDFLARE_API_TOKEN}`,
            'Content-Type': 'application/json',
            'Content-Length': Buffer.byteLength(body)
          },
          timeout: 25000
        }, (res) => {
          let data = '';
          res.on('data', c => data += c);
          res.on('end', () => {
            if (res.statusCode >= 200 && res.statusCode < 300) {
              try {
                const parsed = JSON.parse(data);
                const text = parsed.result?.response || parsed.result?.text || '';
                resolve(text);
              } catch (e) {
                reject(e);
              }
            } else {
              reject(new Error(`Cloudflare HTTP ${res.statusCode}: ${data.slice(0, 150)}`));
            }
          });
        });
        req.on('error', reject);
        req.on('timeout', () => { req.destroy(); reject(new Error('Cloudflare request timed out')); });
        req.write(body);
        req.end();
      });

      const cleaned = validateAndCleanEpisode(raw, topic);
      if (cleaned) {
        return { plan: cleaned, provider: `cloudflare/${model}` };
      }
    } catch (e) {
      console.warn(`[AI Planner] Cloudflare AI (${model}) failed:`, e.message);
    }
  }
  throw new Error('All Cloudflare AI models failed');
}

/**
 * Primary Multi-Provider Planning Function
 * Strictly attempts real AI models in order: Gemini -> Groq -> OpenAI -> OpenRouter -> Cloudflare.
 * If all fail, throws an actionable error.
 */
async function generateCartoonEpisodePlan(topic) {
  const targetTopic = (topic || 'How Undersea Cables Connect the Global Internet').trim();
  const errors = [];

  // 1. Try Google Gemini (Primary)
  try {
    const res = await callGemini(targetTopic);
    console.log(`[AI Planner] ✅ Successfully generated plan via ${res.provider}`);
    return { ...res.plan, modelUsed: res.provider };
  } catch (err) {
    errors.push(`Gemini: ${err.message}`);
  }

  // 2. Try Groq (Backup 1)
  try {
    const res = await callGroq(targetTopic);
    console.log(`[AI Planner] ✅ Successfully generated plan via ${res.provider}`);
    return { ...res.plan, modelUsed: res.provider };
  } catch (err) {
    errors.push(`Groq: ${err.message}`);
  }

  // 3. Try OpenAI (Backup 2)
  try {
    const res = await callOpenAI(targetTopic);
    console.log(`[AI Planner] ✅ Successfully generated plan via ${res.provider}`);
    return { ...res.plan, modelUsed: res.provider };
  } catch (err) {
    errors.push(`OpenAI: ${err.message}`);
  }

  // 4. Try OpenRouter (Backup 3)
  try {
    const res = await callOpenRouter(targetTopic);
    console.log(`[AI Planner] ✅ Successfully generated plan via ${res.provider}`);
    return { ...res.plan, modelUsed: res.provider };
  } catch (err) {
    errors.push(`OpenRouter: ${err.message}`);
  }

  // 5. Try Cloudflare Workers AI (Backup 4)
  try {
    const res = await callCloudflareAI(targetTopic);
    console.log(`[AI Planner] ✅ Successfully generated plan via ${res.provider}`);
    return { ...res.plan, modelUsed: res.provider };
  } catch (err) {
    errors.push(`Cloudflare: ${err.message}`);
  }

  // No deterministic fallback. Throw explicit error with all provider failures.
  const errorMessage = `[AI Planner] All AI model providers failed to generate episode plan for topic "${targetTopic}".\nProvider diagnostics:\n- ${errors.join('\n- ')}`;
  console.error(errorMessage);
  throw new Error(errorMessage);
}

module.exports = {
  generateCartoonEpisodePlan,
  validateAndCleanEpisode
};
